name: build-windows

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show tool versions
        run: |
          cmake --version
          ninja --version || echo "ninja not present (CMake will pick MSBuild)"

      - name: Install vcpkg + SFML
        shell: powershell
        run: |
          git clone https://github.com/microsoft/vcpkg $env:VCPKG_ROOT
          $env:VCPKG_ROOT\bootstrap-vcpkg.bat
          $env:VCPKG_ROOT\vcpkg.exe install sfml:x64-windows

      - name: Configure (CMake)
        shell: powershell
        run: |
          cmake -S . -B build `
            -G "Ninja" `
            -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT\scripts\buildsystems\vcpkg.cmake" `
            -DVCPKG_TARGET_TRIPLET=x64-windows

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Install to dist/
        run: cmake --install build --config Release --prefix dist

      - name: Copy runtime DLLs from vcpkg
        shell: powershell
        run: |
          New-Item -ItemType Directory -Force -Path dist | Out-Null
          Copy-Item "$env:VCPKG_ROOT\installed\x64-windows\bin\*.dll" dist -ErrorAction SilentlyContinue
          # иногда зависимости лежат и в bin, и в debug/bin — оставим только Release:
          Get-ChildItem dist\*.pdb -ErrorAction SilentlyContinue | Remove-Item -Force

      - name: Zip
        shell: powershell
        run: |
          if (Test-Path Sokoban-Windows.zip) { Remove-Item Sokoban-Windows.zip -Force }
          Compress-Archive -Path dist\* -DestinationPath Sokoban-Windows.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Sokoban-Windows
          path: Sokoban-Windows.zip